database:
  host: 127.0.0.1
  port: 5432
  password: admin
  user: admin
  dbName: bets

wager:
  providerURI: "wss://polygon-mumbai.g.alchemy.com/v2/A20qXmbk28bOB0C5P852lsiYhYkFQ_zx"
  wagerAddress: "0xfA217E7f00FFB089Faf570BD2Beed3a0193D9bCd"