database:
  host: backend-db-1
  port: 5432
  password: admin
  user: admin
  dbName: bets

wager:
  providerURI: "wss://polygon-mumbai.g.alchemy.com/v2/A20qXmbk28bOB0C5P852lsiYhYkFQ_zx"
  wagerAddress: "0x0B8400C522AA3185a024684C02c2795654275f20"